language: php

php:
  - 8.1
  - 8.2
  - 8.3

services:
  - mysql

before_script:
  - composer create-project moodlehq/moodle-plugin-ci moodle-plugin-ci ^4

script:
  - moodle-plugin-ci/bin/moodle-plugin-ci validate
  - moodle-plugin-ci/bin/moodle-plugin-ci phplint
  - moodle-plugin-ci/bin/moodle-plugin-ci phpcs
  - moodle-plugin-ci/bin/moodle-plugin-ci mustache

cache:
  directories:
    - $HOME/.composer/cache
