name: Moodle Plugin CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install moodle-plugin-ci
        run: |
          composer create-project moodlehq/moodle-plugin-ci moodle-plugin-ci ^4

      - name: Validate plugin
        run: moodle-plugin-ci/bin/moodle-plugin-ci validate

      - name: PHP Lint
        run: moodle-plugin-ci/bin/moodle-plugin-ci phplint

      - name: Code checker (phpcs)
        run: moodle-plugin-ci/bin/moodle-plugin-ci phpcs

      - name: Mustache lint
        run: moodle-plugin-ci/bin/moodle-plugin-ci mustache
