name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        moodle-branch: ["MOODLE_401_STABLE"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install moodle-plugin-ci
        run: |
          composer create-project moodlehq/moodle-plugin-ci ci ^4

      - name: Run PHPCS
        run: ci/bin/moodle-plugin-ci phpcs

      - name: Run PHPDoc
        run: ci/bin/moodle-plugin-ci phpdoc

      - name: Run PHPUnit
        run: ci/bin/moodle-plugin-ci phpunit
